add thumb for all videos
Borodutch/VideoDownloadBot pull request #11
Opened 2022-02-04 21:04 UTC by Semion120

Добавил создание и обработку превьюх для видосов, проверил на 15 видосах все ок работает

2022-02-04 21:12 UTC, backmeupplz requested changes

2022-02-04 21:12 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +    .catch((err) => {
Наверное, нужно сделать `await` у `sharp`? Не мешай async/await и then/catch

2022-02-04 21:12 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +    .resize(320, 320)
Что, если картинка длинная или высокая? Все равно ресайзнится до 320х320 квадрата?

2022-02-04 21:12 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  let thumbUrl = ''
Не сокращай названия переменных

2022-02-04 21:12 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPath = await downloadThumb(thumbUrl)
Что, если тут `thumbUrl` все еще `''`?

2022-02-04 21:12 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = `${tempDir}/${
Сделай путь через `uuid`, не занимайся хаками с url

2022-02-04 21:12 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  await downloader.download().catch((err) => {
Либо async/await, либо then/catch, не мешай их

2022-02-05 12:15 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    .resize(320, 320)
Да, он автоматом обрезает если что. Почти все превьхи идут альбомной ориентации.

2022-02-05 12:17 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPath = await downloadThumb(thumbUrl)
превьюхи не будет наверное, либо отлетит ошибка
Просто то что я проверял, везде находил хоть какую то превьюху
Что тут следует сделать?

2022-02-05 12:21 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    .catch((err) => {
сделал

2022-02-05 12:21 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  let thumbUrl = ''
поправил

2022-02-05 12:22 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  await downloader.download().catch((err) => {
сделал

2022-02-05 12:32 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = `${tempDir}/${
Сделал везде через uuid в thumbnail

2022-02-06 11:16 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPath = await downloadThumb(thumbUrl)
думаешь добавить обработку какую то? Или просто без превьюхи отправлять?

2022-02-07 15:51 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPath = await downloadThumb(thumbUrl)
Может сделать заглушку, типо если превьюха не загрузилась - сделать дефолтную картиночку?

2022-02-07 19:45 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPath = await downloadThumb(thumbUrl)
Сделать проверку на `''`

2022-02-09 15:05 UTC, backmeupplz requested changes

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  if (thumbnailUrl == '') {
В JS почти никогда не нужно использовать `==`. Используй `===`

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  if (thumbnailUrl == '') {
Здесь можно упростить до `if (!thumbnailUrl)`

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +    thumbnailPath = `${tempDir}/${thumbnailUuid}.jpeg`
Это всегда будет `jpeg`?

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +      seek: '00:04:01',
Почему 4 минуты? Что, если видео короче 4 минут?

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  thumbnailPath = await downloadThumbnail(thumbnailUrl, thumbnailUuid)
Этому файлу тоже нужно сделать `unlink`. Не оставляй лишние файлы в системе.

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +async function downloadThumbnail(url: string, id?: string) {
Почему `id` опционален?

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const path = `${tempDir}/${id}`
Если id пустой, то тут получится `some/path/undefined`

2022-02-09 15:05 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +    .resize(320, 320)
Обрезает или делает fit в 320х320? Если моя картинка 640x320, то какого размера получится после конверсии thumbnail?

2022-02-09 15:17 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    .resize(320, 320)
Он делает на выходе изображение 320-320. То есть он и обрезает и масштабирует по необходимости

2022-02-09 15:18 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +      seek: '00:04:01',
если видео короче 4 минут обычно превьюха не ставится, а начинается автовоспроизведение

2022-02-09 15:19 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +      seek: '00:04:01',
могу поставить 2 минуты
Я не знаю какое в среднем время качают через бота

2022-02-09 15:20 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  thumbnailPath = await downloadThumbnail(thumbnailUrl, thumbnailUuid)
Любой из них удаляется через unlink в downloadUrl

2022-02-09 15:22 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  thumbnailPath = await downloadThumbnail(thumbnailUrl, thumbnailUuid)
return что в случае своей превьюхи что в случае скачки в основном файле виден как thumb, по итогу в анлинке он и будет удален

2022-02-09 15:23 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  thumbnailPath = await downloadThumbnail(thumbnailUrl, thumbnailUuid)
вот, удаляется thumb. По сути нам не важно из какого ретерн приходит сюда путь

2022-02-09 15:24 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const path = `${tempDir}/${id}`
Приянл

2022-02-09 15:24 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +async function downloadThumbnail(url: string, id?: string) {
Принял, будет обязателен

2022-02-09 15:25 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  if (thumbnailUrl == '') {
принял

2022-02-09 15:26 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  if (thumbnailUrl == '') {
принял, постараюсь не забыть

2022-02-09 15:35 UTC, backmeupplz requested changes

2022-02-09 15:35 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  thumbnailPath = await downloadThumbnail(thumbnailUrl, thumbnailUuid)
Это удаляется файл по путю с `L38`. Файл, который качается тут на `L36` имеет другой путь — и он остается

2022-02-09 15:35 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +    .resize(320, 320)
Нужно сделать contain, а не cover

2022-02-09 15:35 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +      seek: '00:04:01',
У меня везде автовоспроизведение выключено. Что буду видеть я на видосах короче 4 минут? Проверь.

2022-02-11 16:24 UTC, backmeupplz commented on package.json
> +    "fluent-ffmpeg": "^2.1.2",
Нужны и `ffmpeg-static`, и `fluent-ffmpeg`? Или только один?

2022-02-11 16:25 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  unlinkSync(thumbnailPath)
У нас, вроде как, есть функция-обертка для `unlinkSync`, которая делает `try/catch`, используй ее

2022-02-11 16:25 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = `${tempDir}/${thumbnailUuid}.jpeg`
Здесь надо делать `resolve`, как и в других местах с `tempDir`

2022-02-11 16:26 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  return await new Promise((res) => {
Тебе не нужно делать `return await`

2022-02-11 16:27 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +      if (data.format.duration) {
А что, если нет `data.format.duration`?  Кинь ошибку

2022-02-11 16:28 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +async function getVideoDuration(videoPath: string): Promise<string> {
Тебе не нужно тут указывать возвращаемый тип, тебе нужно на `L62` сделать `Promise<string>`

2022-02-11 16:28 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +          `${
Это дикие хаки. Найди способ использовать библиотеку, которая форматирует количество секунд в строку часов, минут и секунд

2022-02-12 08:33 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +          `${
зато считает точно XD, есть библиотека для этого как раз momentjs. Тогда ее попробую

2022-02-12 09:05 UTC, Semion120 commented on package.json
> +    "fluent-ffmpeg": "^2.1.2",
они используются в разных библиотеках. fluent - показывает длительность видео, static - выдает путь до папки с ffmpeg для либы которая создает превьюхи

2022-02-12 09:05 UTC, Semion120 commented on package.json
> +    "fluent-ffmpeg": "^2.1.2",
Лучше оставить оба?

2022-02-12 09:13 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  unlinkSync(thumbnailPath)
Эта обертка находится в доке downloadUrl, мне сделать чтобы главная функция возвращала помимо пути к превью еще и путь к файлу на удалению? Или может проще сделать в этом файле try/catch?

2022-02-12 09:17 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = `${tempDir}/${thumbnailUuid}.jpeg`
понял кажется, сделаю

2022-02-12 09:17 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  return await new Promise((res) => {
понял

2022-02-12 09:17 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +      if (data.format.duration) {
окей

2022-02-12 09:20 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +async function getVideoDuration(videoPath: string): Promise<string> {
понял

2022-02-12 16:33 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +          `${
вероятность, что считает точно, ниже, чем если использовать готовое и оттестированное в продакшене решение

2022-02-12 16:35 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  unlinkSync(thumbnailPath)
У тебя `unlinkSync` может кинуть exception, если `thumbnailPath` по какой-то причине не существует. Поэтому `unilnkSync` нужно обернуть в `try/catch`. Для этого можно вынести в отдельный файл функцию:
```typescript
function unlincSyncSafe(path: string) {
  try {
    unlinkSync(path)
  } catch (error) {
    console.error(`Error unlinking ${path}: ${error}`)
  }
}
```

2022-02-12 16:36 UTC, backmeupplz commented on package.json
> +    "fluent-ffmpeg": "^2.1.2",
Лучше использовать один, если возможно

2022-02-15 15:25 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const path = `${tempDir}/${id}`
Здесь нужно использовать `resolve`

2022-02-15 15:29 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = `${tempDir}/${thumbnailUuid}.jpeg`
А еще это будет тот же путь и файл, что на `L33` (если ты там тоже укажешь расширение), что приведет к проблемам после `L40`

2022-02-16 09:50 UTC, Semion120 commented on src/helpers/downloadUrl.ts
> +    console.log('Превью получено')
Забыл удалить, прошу прощения

2022-02-16 09:51 UTC, Semion120 commented on src/helpers/downloadUrl.ts
>      try {
сделал

2022-02-16 09:51 UTC, Semion120 commented on src/helpers/unlincSyncSafe.ts
> +    console.error(`Error unlinking ${path}: ${error}`)
сделал

2022-02-16 09:54 UTC, Semion120 commented on src/models/DownloadedFileInfo.ts
> +    format?: string
да в общем то не используется в коде удалю

2022-02-16 09:55 UTC, Semion120 commented on package.json
> +    "@types/ffmpeg-static": "^3.0.1",
убрал

2022-02-16 09:56 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    filename: `${uuid}.jpeg`,
![image](https://user-images.githubusercontent.com/71780642/154240122-56266588-a870-4a67-8263-5b0526ef1461.png)
тут написанно ввести паттерн, то есть как я понял - это я выбираю формат на выходе

2022-02-16 10:00 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    size: '320x320',
нет, я могу тут делать превью без размера и пропустить его через шарп, чтобы сделать contain

2022-02-16 10:07 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    filename: `${uuid}.jpeg`,
не очень понял, что тут сделать. Я просто создал сверху переменную filname :)

2022-03-02 21:58 UTC, backmeupplz requested changes

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +      .on('end', () => resolve('Done'))
Не кидай строку в `resolve`, которую не будешь использовать. Просто вызови `resolve`. Может, нужно будет на `L55` указать тип возврата промиса типа `return new Promise<void>(...`

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  return new Promise((resolve, rej) => {
Либо сокращай оба слова (`res, rej`), либо ни то, ни то (`resolve, reject`)

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const path = resolve(tempDir, `${id}-downloadUrl`)
Что за хаки с магическими строками? Почему `downloadUrl`? Избавься от этого.

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +    destFile: path,
Если переменную назовешь `destFile` сразу, то сможешь тут сделать `destFile,`

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = resolve(tempDir, `${thumbnailUuid}-done.jpeg`)
Что за хаки с магической строкой `-done`?

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const path = resolve(tempDir, `${id}-downloadUrl`)
Этот файл удаляется после?

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const outputPath = resolve(tempDir, `${thumbnailUuid}-done.jpeg`)
Этот файл удаляется после?

2022-03-02 21:58 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPathDone = await resizeThumb(thumbnailPath, outputPath)
Выглядит повтором `L34`

2022-03-02 21:59 UTC, upacyxou commented on src/helpers/getThumbnailUrl.ts
> +      .on('end', () => resolve('Done'))
не обязательно передавать стрелочную функцию в колбек, можешь сделать ` .on('end', resolve)`

2022-03-02 22:14 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +      .on('end', () => resolve('Done'))
Понял, сделал

2022-03-02 22:14 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  return new Promise((resolve, rej) => {
Оба сократил, так выглядит аккуратнее

2022-03-02 22:16 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const path = resolve(tempDir, `${id}-downloadUrl`)
Это я с делал, чтобы отличать какие файлы из какой ветки. Сейчас в этом нет смысла, удалил. Файл удаляется, строка L40

2022-03-02 22:17 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +    destFile: path,
Сделал

2022-03-02 22:27 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPathDone = await resizeThumb(thumbnailPath, outputPath)
Это и есть повтор по сути, тут есть 2 ветки: превью из yt-dlp и собственное превью с помощью ffmpeg. Каждая из них обрабатывается в отдельности, поэтому функцию ресайза я вынес отдельно, чтобы использовать в двух местах. 

Я могу поменять названия переменных, могу попробовать сделать чтобы ресайз делался в одном месте. типо сначала проходит ветвение, а потом функция сливается обратно в один поток где происходит ресайз и возврат

2022-03-02 22:27 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +      .on('end', () => resolve('Done'))
Сделал

2022-03-02 22:36 UTC, backmeupplz commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPathDone = await resizeThumb(thumbnailPath, outputPath)
Поменяй последовательность таким образом, чтобы `resizeThumb` вызывался один раз

2022-03-02 22:40 UTC, Semion120 commented on src/helpers/getThumbnailUrl.ts
> +  const thumbPathDone = await resizeThumb(thumbnailPath, outputPath)
сделал

2022-03-03 02:09 UTC, merged