Add message about big video size
Borodutch/VideoDownloadBot pull request #7
Opened 2021-12-28 07:59 UTC by Semion120

2022-01-05 22:37 UTC, backmeupplz requested changes

2022-01-05 22:37 UTC, backmeupplz commented on src/helpers/downloadUrl.ts
> +        ? 'bestaudio[filesize<=?2G][filesize<=2048]/[filesize_approx<=2048M]'
`bestaudio[filesize<=2G]/[filesize_approx<=2G]`

2022-01-05 22:37 UTC, backmeupplz commented on src/helpers/downloadUrl.ts
> +        : '[filesize<=?2G][filesize<=2048]/[filesize_approx<=2048M]',
`[filesize<=2G]/[filesize_approx<=2G]`

2022-01-05 22:37 UTC, backmeupplz commented on src/helpers/downloadUrl.ts
> +    console.log(downloadJob.status)
Не пушь лишние `console.log`

2022-01-05 22:37 UTC, backmeupplz commented on src/helpers/downloadUrl.ts
> +        console.log(error.message)
Не пушь лишние `console.log`

2022-01-10 07:23 UTC, Semion120 commented on src/helpers/downloadUrl.ts
> +        ? 'bestaudio[filesize<=?2G][filesize<=2048]/[filesize_approx<=2048M]'
сделал

2022-01-10 07:23 UTC, Semion120 commented on src/helpers/downloadUrl.ts
> +        : '[filesize<=?2G][filesize<=2048]/[filesize_approx<=2048M]',
сделал

2022-01-10 07:23 UTC, Semion120 commented on src/helpers/downloadUrl.ts
> +    console.log(downloadJob.status)
удалил

2022-01-10 07:23 UTC, Semion120 commented on src/helpers/downloadUrl.ts
> +        console.log(error.message)
убрал

2022-01-10 19:59 UTC, backmeupplz requested changes

2022-01-10 19:59 UTC, backmeupplz commented on src/helpers/downloadUrl.ts
> +        : '[filesize<=?2G][filesize<=2G]/[filesize_approx<=2G]',
Тут можно убрать `[filesize<=?2G]`

2022-01-10 19:59 UTC, backmeupplz commented on src/models/DownloadJobStatus.ts
> +  noSuitableVideoSize = 'nosuitabnoSuitableVideoSizele',
Опечатка

2022-01-11 17:28 UTC, merged